name: test

on: push

jobs:
  test:
    name: test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: echo
        run: echo 'Hello world'
      - name: istall
        run: npm ci
      - name: exec
        run: node app.js

